
language: en
pipeline:
  - name: WhitespaceTokenizer
    intent_tokenization_flag: True
    intent_split_symbol: "+"
  - name: "sentiment_analysis.SentimentAnalyzer"
  - name: RegexFeaturizer #Creates a vector representation of user message using regular expressions.
  - name: LexicalSyntacticFeaturizer #Creates lexical and syntactic features for a user message to support entity extraction
  - name: CountVectorsFeaturizer #Creates bag-of-words representation of user messages, intents, and responses.
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    random_seed: 42
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1
policies:
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy #The Transformer Embedding Dialogue (TED) Policy is a multi-task architecture for next action prediction and entity recognition
    max_history: 5
    epochs: 100
    constrain_similarities: true
    random_seed: 42
  - name: RulePolicy
    core_fallback_threshold: 0.6
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
    #rasa run -m models --enable-api --cors "*" --debug